name: Publish Pipeline

on:
  release:
    types: [ created ]

jobs:
  publish:
    # 실행 환경 (Git Runners 개인 서버)
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      # JDK 17 세팅
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: setup gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}