name: Publish Pipeline

on:
  release:
    types: [ created ]

jobs:
  build:
    # 실행 환경 (Git Runners 개인 서버)
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      # JDK 17 세팅
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # 빌드
      - name: Build with Gradle
        run: ./gradlew build

      # artifacts 업로드
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: common-utils
          path: build/libs/*.jar

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}